import * as stylex from '@stylexjs/stylex'

const colors = {
  ink: '#25241f',
  muted: '#716e64',
  card: '#fffdf8',
  line: '#ded8ca',
  orange: '#e8632e',
  orangeDark: '#bd4520',
  green: '#315f4a',
  softGreen: '#dfe9df',
}

const fonts = {
  display: 'Manrope, system-ui, sans-serif',
}

const narrow = '@media (max-width: 700px)'
const tablet = '@media (max-width: 960px)'
const motion = '@media (prefers-reduced-motion: no-preference)'

export const styles = stylex.create({
  appShell: {
    width: 'min(1240px, calc(100% - 48px))',
    margin: '0 auto',
    paddingBottom: 80,
    [narrow]: { width: 'min(100% - 28px, 1240px)', paddingBottom: 48 },
  },
  topbar: {
    display: 'flex',
    alignItems: 'center',
    justifyContent: 'space-between',
    minHeight: 88,
    borderBottom: `1px solid ${colors.line}`,
    [narrow]: { minHeight: 72 },
  },
  logo: {
    display: 'inline-flex',
    alignItems: 'center',
    gap: 10,
    fontFamily: fonts.display,
    fontSize: 20,
    fontWeight: 800,
    letterSpacing: '-0.04em',
  },
  logoMark: {
    position: 'relative',
    display: 'inline-grid',
    width: 34,
    height: 34,
    placeItems: 'center',
    border: `3px solid ${colors.orange}`,
    borderRadius: '50%',
    '::before': {
      position: 'absolute',
      left: 8,
      width: 3,
      height: 17,
      content: '',
      background: colors.orange,
      borderRadius: 10,
    },
    '::after': {
      position: 'absolute',
      right: 8,
      width: 3,
      height: 17,
      content: '',
      background: colors.orange,
      borderRadius: 10,
    },
  },
  logoMarkCenter: {
    position: 'absolute',
    width: 10,
    height: 3,
    background: colors.orange,
    borderRadius: 10,
  },
  homeChip: {
    display: 'flex',
    alignItems: 'center',
    gap: 8,
    padding: '8px 13px',
    border: `1px solid ${colors.line}`,
    borderRadius: 999,
    color: colors.muted,
    background: 'rgb(255 253 248 / 64%)',
    fontSize: 13,
    fontWeight: 600,
  },
  homeDot: {
    width: 7,
    height: 7,
    borderRadius: '50%',
    background: '#6d9c76',
    boxShadow: '0 0 0 3px rgb(109 156 118 / 15%)',
  },
  signOutButton: {
    marginLeft: 4,
    color: colors.orangeDark,
    fontSize: 12,
    fontWeight: 700,
  },
  hero: {
    display: 'grid',
    gridTemplateColumns: 'minmax(0, 1.35fr) minmax(260px, 0.65fr)',
    gap: 48,
    alignItems: 'end',
    padding: '72px 0 68px',
    [tablet]: { gridTemplateColumns: '1fr', gap: 24, padding: '56px 0 50px' },
    [narrow]: { padding: '44px 0' },
  },
  eyebrow: {
    marginBottom: 9,
    color: colors.orangeDark,
    fontSize: 11,
    fontWeight: 700,
    letterSpacing: '0.14em',
    textTransform: 'uppercase',
  },
  eyebrowLight: { color: '#bbd7c1' },
  heroTitle: {
    maxWidth: 780,
    fontFamily: fonts.display,
    fontSize: 'clamp(42px, 6vw, 78px)',
    lineHeight: 0.98,
    letterSpacing: '-0.065em',
    [narrow]: { fontSize: 44 },
  },
  heroCopy: {
    maxWidth: 390,
    paddingBottom: 5,
    color: colors.muted,
    fontSize: 17,
    lineHeight: 1.65,
    [narrow]: { fontSize: 15 },
  },
  status: {
    margin: '-38px 0 34px',
    padding: '11px 14px',
    borderLeft: `3px solid ${colors.orange}`,
    color: '#6e381f',
    background: '#f7dfcf',
    fontSize: 14,
    [narrow]: { marginTop: -22 },
  },
  sectionHeading: {
    display: 'flex',
    alignItems: 'end',
    justifyContent: 'space-between',
    marginBottom: 20,
  },
  compactHeading: { paddingBottom: 14, borderBottom: `1px solid ${colors.line}` },
  sectionTitle: {
    fontFamily: fonts.display,
    fontSize: 25,
    letterSpacing: '-0.04em',
  },
  sectionMeta: { paddingBottom: 4, color: colors.muted, fontSize: 13 },
  weekGrid: {
    display: 'grid',
    gridTemplateColumns: 'repeat(7, minmax(0, 1fr))',
    overflow: 'hidden',
    border: `1px solid ${colors.line}`,
    borderRadius: 18,
    background: colors.card,
    boxShadow: '0 16px 50px rgb(55 43 25 / 8%)',
    [tablet]: { gridTemplateColumns: 'repeat(7, minmax(135px, 1fr))', overflowX: 'auto' },
  },
  dayCard: {
    position: 'relative',
    display: 'flex',
    minWidth: 0,
    minHeight: 210,
    flexDirection: 'column',
    padding: '17px 15px 15px',
    borderRight: `1px solid ${colors.line}`,
    ':last-child': { borderRight: 0 },
  },
  today: {
    '::before': {
      position: 'absolute',
      top: 0,
      right: 12,
      left: 12,
      height: 3,
      content: '',
      background: colors.orange,
      borderRadius: '0 0 4px 4px',
    },
  },
  planned: { background: '#faf3e8' },
  dayDate: {
    display: 'flex',
    alignItems: 'baseline',
    justifyContent: 'space-between',
    color: colors.muted,
  },
  weekday: { fontSize: 12, fontWeight: 700, textTransform: 'uppercase' },
  dayNumber: { color: colors.ink, fontFamily: fonts.display, fontSize: 25 },
  mealContent: {
    display: 'flex',
    minHeight: 135,
    flex: 1,
    flexDirection: 'column',
    justifyContent: 'space-between',
    paddingTop: 33,
  },
  mealName: {
    overflowWrap: 'anywhere',
    fontFamily: fonts.display,
    fontSize: 17,
    fontWeight: 700,
    lineHeight: 1.25,
    letterSpacing: '-0.025em',
  },
  mealActions: { display: 'flex', alignItems: 'center', justifyContent: 'space-between', gap: 5 },
  bareButton: { padding: 0, border: 0, background: 'transparent' },
  textButton: { color: colors.green, fontSize: 12, fontWeight: 700 },
  iconButton: {
    display: 'grid',
    width: 27,
    height: 27,
    flex: '0 0 27px',
    placeItems: 'center',
    borderRadius: '50%',
    color: colors.muted,
    fontSize: 18,
    ':hover': { background: 'rgb(37 36 31 / 7%)' },
  },
  emptyMeal: {
    display: 'flex',
    minHeight: 135,
    flex: 1,
    alignItems: 'center',
    justifyContent: 'center',
    gap: 6,
    color: '#918d83',
    fontSize: 12,
    ':hover': { color: colors.orangeDark },
  },
  plus: { fontSize: 18, fontWeight: 300 },
  eatenLabel: {
    alignSelf: 'flex-start',
    padding: '5px 9px',
    borderRadius: 999,
    color: colors.green,
    background: colors.softGreen,
    fontSize: 11,
    fontWeight: 700,
  },
  contentGrid: {
    display: 'grid',
    gridTemplateColumns: 'repeat(2, minmax(0, 1fr))',
    gap: 24,
    marginTop: 56,
    [narrow]: { gridTemplateColumns: '1fr', marginTop: 38 },
  },
  panel: {
    padding: 30,
    border: `1px solid ${colors.line}`,
    borderRadius: 18,
    background: colors.card,
    [narrow]: { padding: 24 },
  },
  planPanel: { color: '#f9f6ee', borderColor: colors.green, background: colors.green },
  stackedForm: {
    display: 'grid',
    gridTemplateColumns: 'minmax(0, 1fr) minmax(0, 1fr) auto',
    gap: 14,
    alignItems: 'end',
    marginTop: 26,
    [tablet]: { gridTemplateColumns: '1fr' },
  },
  formLabel: { display: 'grid', gap: 7, fontSize: 12, fontWeight: 700 },
  field: {
    width: '100%',
    height: 46,
    padding: '0 13px',
    border: '1px solid #d5d0c4',
    borderRadius: 9,
    background: '#fff',
    fontSize: 14,
  },
  planSelect: { color: colors.ink, borderColor: 'rgb(255 255 255 / 20%)', background: '#f9f6ee' },
  actionButton: {
    minHeight: 46,
    padding: '0 19px',
    borderRadius: 9,
    fontSize: 13,
    fontWeight: 700,
    [motion]: { transition: 'color 140ms ease, background 140ms ease, transform 140ms ease' },
    ':active': { transform: 'translateY(1px)' },
  },
  primaryButton: {
    border: '1px solid #f5b391',
    color: '#4a2011',
    background: '#f3a078',
    ':hover': { background: '#f8ae89' },
  },
  secondaryButton: {
    border: `1px solid ${colors.ink}`,
    color: '#fff',
    background: colors.ink,
    ':hover': { background: '#3c3a33' },
  },
  optional: { color: colors.muted, fontWeight: 400 },
  emptyCopy: {
    maxWidth: 430,
    marginTop: 20,
    color: 'inherit',
    opacity: 0.72,
    fontSize: 14,
    lineHeight: 1.55,
  },
  lowerGrid: { gap: 56, marginTop: 64, [narrow]: { gap: 42, marginTop: 50 } },
  list: { display: 'grid' },
  dishRow: {
    display: 'flex',
    minHeight: 76,
    alignItems: 'center',
    justifyContent: 'space-between',
    gap: 20,
    borderBottom: `1px solid ${colors.line}`,
  },
  dishTitle: { fontFamily: fonts.display, fontSize: 15, letterSpacing: '-0.02em' },
  dishNotes: { marginTop: 3, color: colors.muted, fontSize: 12 },
  dishStat: {
    flex: '0 0 auto',
    marginTop: 3,
    color: colors.muted,
    fontSize: 12,
    textAlign: 'right',
  },
  historyRow: {
    display: 'grid',
    minHeight: 58,
    gridTemplateColumns: '12px minmax(0, 1fr) auto',
    gap: 12,
    alignItems: 'center',
    borderBottom: `1px solid ${colors.line}`,
    fontSize: 13,
  },
  historyName: { fontWeight: 600 },
  historyDate: { color: colors.muted, fontSize: 12 },
  historyMark: { width: 8, height: 8, border: `2px solid ${colors.orange}`, borderRadius: '50%' },
  listEmpty: { margin: '10px 0 0', padding: '18px 0', color: colors.muted },
  setupShell: { display: 'grid', minHeight: '100vh', padding: 24, placeItems: 'center' },
  setupCard: {
    width: 'min(560px, 100%)',
    padding: 44,
    border: `1px solid ${colors.line}`,
    borderRadius: 22,
    background: colors.card,
    boxShadow: '0 16px 50px rgb(55 43 25 / 8%)',
    [narrow]: { padding: '30px 24px' },
  },
  setupEyebrow: { marginTop: 42 },
  setupTitle: {
    fontFamily: fonts.display,
    fontSize: 'clamp(32px, 7vw, 52px)',
    lineHeight: 1.02,
    letterSpacing: '-0.055em',
  },
  setupCopy: { marginTop: 20, color: colors.muted, lineHeight: 1.65 },
  signInButton: {
    display: 'inline-flex',
    minHeight: 48,
    alignItems: 'center',
    justifyContent: 'center',
    marginTop: 28,
    padding: '0 20px',
    borderRadius: 9,
    color: '#fff',
    background: colors.ink,
    fontSize: 14,
    fontWeight: 700,
    textDecoration: 'none',
    ':hover': { background: '#3c3a33' },
  },
})
