import * as stylex from '@stylexjs/stylex'

const colors = {
  ink: '#26352f',
  muted: '#727b75',
  cream: '#fff9e9',
  white: '#fffef9',
  line: '#e7dfc8',
  coral: '#ef6349',
  coralSoft: '#f4a28f',
  yellow: '#fbd976',
  green: '#293a34',
  mint: '#dfece2',
}

const display = 'Manrope, system-ui, sans-serif'
const tablet = '@media (min-width: 720px)'
const mobile = '@media (max-width: 719px)'
const motion = '@media (prefers-reduced-motion: no-preference)'

export const styles = stylex.create({
  appShell: {
    width: 'min(100% - 32px, 1080px)',
    margin: '0 auto',
    paddingBottom: 116,
    [tablet]: { width: 'min(100% - 64px, 1080px)', paddingBottom: 80 },
  },
  topbar: {
    position: 'relative',
    zIndex: 3,
    display: 'flex',
    minHeight: 76,
    alignItems: 'center',
    justifyContent: 'space-between',
    [tablet]: { minHeight: 92 },
  },
  logo: {
    display: 'inline-flex',
    alignItems: 'center',
    gap: 8,
    fontFamily: display,
    fontSize: 19,
    fontWeight: 800,
    letterSpacing: '-0.045em',
  },
  logoMark: { display: 'inline-flex', width: 27, height: 27, color: colors.coral },
  icon: { display: 'block', width: 20, height: 20, flex: '0 0 auto' },
  iconFill: { width: '100%', height: '100%' },
  account: { display: 'flex', alignItems: 'center', gap: 10 },
  avatar: {
    display: 'grid',
    width: 34,
    height: 34,
    placeItems: 'center',
    border: 0,
    borderRadius: '50%',
    color: '#fff',
    backgroundColor: colors.green,
    fontSize: 12,
    fontWeight: 800,
  },
  bareButton: { padding: 0, border: 0, backgroundColor: 'transparent' },
  signOutButton: {
    color: colors.muted,
    fontSize: 11,
    fontWeight: 700,
    [mobile]: {
      position: 'absolute',
      width: 1,
      height: 1,
      overflow: 'hidden',
      clip: 'rect(0 0 0 0)',
    },
    ':hover': { color: colors.coral },
  },
  hero: {
    position: 'relative',
    padding: '38px 0 36px',
    [tablet]: { padding: '66px 0 54px' },
  },
  greeting: { color: colors.muted, fontSize: 14, [tablet]: { fontSize: 16 } },
  heroTitle: {
    maxWidth: 760,
    marginTop: 4,
    fontFamily: display,
    fontSize: 'clamp(40px, 7vw, 72px)',
    lineHeight: 0.98,
    letterSpacing: '-0.065em',
  },
  heroCopy: { marginTop: 12, color: colors.muted, fontSize: 13, [tablet]: { fontSize: 15 } },
  sunDoodle: {
    position: 'absolute',
    top: 36,
    right: 5,
    width: 45,
    height: 45,
    color: '#df5338',
    transform: 'rotate(10deg)',
    [tablet]: { top: 68, right: 28, width: 64, height: 64 },
  },
  status: {
    margin: '-16px 0 26px',
    padding: '11px 14px',
    borderRadius: 12,
    color: '#633a2e',
    backgroundColor: '#f8d9ce',
    fontSize: 13,
  },
  weekSection: { scrollMarginTop: 20 },
  sectionHeading: {
    display: 'flex',
    alignItems: 'baseline',
    justifyContent: 'space-between',
    gap: 16,
    marginBottom: 16,
  },
  sectionTitle: {
    fontFamily: display,
    fontSize: 21,
    lineHeight: 1.1,
    letterSpacing: '-0.04em',
    [tablet]: { fontSize: 25 },
  },
  sectionMeta: { color: colors.muted, fontSize: 11, [tablet]: { fontSize: 13 } },
  dayPills: {
    display: 'grid',
    gridTemplateColumns: 'repeat(7, minmax(43px, 1fr))',
    gap: 7,
    overflowX: 'auto',
    paddingBottom: 2,
    scrollbarWidth: 'none',
    [tablet]: { gap: 12 },
  },
  dayPill: {
    position: 'relative',
    display: 'grid',
    minWidth: 43,
    height: 66,
    gap: 1,
    placeItems: 'center',
    padding: '7px 2px',
    border: `1px solid ${colors.line}`,
    borderRadius: 24,
    color: colors.muted,
    backgroundColor: 'rgb(255 255 255 / 72%)',
    [tablet]: { height: 72 },
    [motion]: { transition: 'color 150ms ease, background-color 150ms ease, transform 150ms ease' },
    ':active': { transform: 'scale(0.97)' },
  },
  dayPillActive: { borderColor: colors.green, color: '#fff', backgroundColor: colors.green },
  dayLetter: { fontSize: 9, fontWeight: 800 },
  dayNumber: { color: colors.ink, fontFamily: display, fontSize: 15 },
  dayNumberActive: { color: '#fff' },
  planDot: {
    position: 'absolute',
    bottom: 6,
    width: 4,
    height: 4,
    borderRadius: '50%',
    backgroundColor: colors.coral,
  },
  dinnerCard: {
    position: 'relative',
    minHeight: 300,
    marginTop: 22,
    padding: 20,
    overflow: 'hidden',
    borderRadius: 28,
    backgroundColor: colors.coralSoft,
    boxShadow: '0 14px 28px rgb(110 73 57 / 12%)',
    [tablet]: { minHeight: 350, marginTop: 28, padding: 28 },
  },
  emptyDinnerCard: { backgroundColor: '#f4c79f' },
  cardTopline: {
    position: 'relative',
    zIndex: 2,
    display: 'flex',
    alignItems: 'center',
    justifyContent: 'space-between',
    color: '#674a42',
    fontSize: 9,
    fontWeight: 800,
    letterSpacing: '0.08em',
    textTransform: 'uppercase',
  },
  todayLabel: { padding: '4px 7px', borderRadius: 999, backgroundColor: 'rgb(255 249 233 / 58%)' },
  foodDoodle: {
    position: 'absolute',
    top: 48,
    right: -8,
    display: 'grid',
    width: 148,
    height: 148,
    placeItems: 'center',
    border: '2px solid rgb(255 249 233 / 72%)',
    borderRadius: '50%',
    color: colors.cream,
    transform: 'rotate(7deg)',
    [tablet]: { top: 58, right: 38, width: 205, height: 205 },
  },
  dinnerName: {
    position: 'relative',
    zIndex: 1,
    maxWidth: '62%',
    marginTop: 130,
    fontFamily: display,
    fontSize: 28,
    lineHeight: 1.02,
    letterSpacing: '-0.05em',
    overflowWrap: 'anywhere',
    [tablet]: { maxWidth: '55%', marginTop: 156, fontSize: 40 },
  },
  cardActions: {
    position: 'absolute',
    right: 20,
    bottom: 20,
    left: 20,
    zIndex: 2,
    display: 'flex',
    alignItems: 'center',
    justifyContent: 'space-between',
    gap: 12,
    [tablet]: { right: 28, bottom: 28, left: 28 },
  },
  ateButton: {
    display: 'inline-flex',
    minHeight: 42,
    alignItems: 'center',
    gap: 7,
    padding: '0 15px',
    border: 0,
    borderRadius: 999,
    color: '#fff',
    backgroundColor: colors.green,
    fontSize: 11,
    fontWeight: 800,
  },
  removeButton: {
    padding: 8,
    border: 0,
    color: '#674a42',
    backgroundColor: 'transparent',
    fontSize: 10,
    fontWeight: 700,
  },
  eatenLabel: {
    position: 'absolute',
    bottom: 22,
    left: 20,
    display: 'inline-flex',
    alignItems: 'center',
    gap: 6,
    padding: '8px 12px',
    borderRadius: 999,
    color: colors.green,
    backgroundColor: colors.mint,
    fontSize: 11,
    fontWeight: 800,
  },
  emptyDinner: { display: 'grid', minHeight: 242, placeItems: 'center', alignContent: 'center' },
  emptyPlate: {
    display: 'grid',
    width: 58,
    height: 58,
    placeItems: 'center',
    border: `2px dashed ${colors.cream}`,
    borderRadius: '50%',
    color: colors.cream,
  },
  emptyTitle: { marginTop: 12, fontFamily: display, fontSize: 21, letterSpacing: '-0.04em' },
  emptyCardCopy: { marginTop: 3, color: '#674a42', fontSize: 11 },
  pickDinnerButton: {
    display: 'inline-flex',
    minHeight: 39,
    alignItems: 'center',
    marginTop: 16,
    padding: '0 15px',
    borderRadius: 999,
    color: '#fff',
    backgroundColor: colors.green,
    fontSize: 11,
    fontWeight: 800,
    textDecoration: 'none',
  },
  panel: { marginTop: 38, padding: 22, borderRadius: 26, [tablet]: { marginTop: 54, padding: 30 } },
  planPanel: { scrollMarginTop: 20, color: colors.cream, backgroundColor: colors.green },
  panelHeading: { display: 'flex', alignItems: 'center', gap: 13 },
  panelIcon: {
    display: 'grid',
    width: 42,
    height: 42,
    flex: '0 0 42px',
    placeItems: 'center',
    borderRadius: '50%',
    color: colors.green,
    backgroundColor: colors.yellow,
  },
  eyebrow: {
    marginBottom: 5,
    color: colors.coral,
    fontSize: 9,
    fontWeight: 800,
    letterSpacing: '0.12em',
    textTransform: 'uppercase',
  },
  eyebrowLight: { color: '#bbd7c1' },
  stackedForm: {
    display: 'grid',
    gap: 13,
    marginTop: 22,
    [tablet]: { gridTemplateColumns: 'minmax(0, 1fr) minmax(0, 1fr) auto', alignItems: 'end' },
  },
  formLabel: { display: 'grid', gap: 7, fontSize: 11, fontWeight: 800 },
  field: {
    width: '100%',
    height: 47,
    padding: '0 13px',
    border: `1px solid ${colors.line}`,
    borderRadius: 13,
    backgroundColor: colors.white,
    fontSize: 13,
  },
  planSelect: {
    color: colors.ink,
    borderColor: 'rgb(255 255 255 / 22%)',
    backgroundColor: colors.cream,
  },
  actionButton: {
    minHeight: 47,
    padding: '0 18px',
    borderRadius: 13,
    fontSize: 12,
    fontWeight: 800,
    [motion]: { transition: 'transform 140ms ease, background-color 140ms ease' },
    ':active': { transform: 'translateY(1px)' },
  },
  primaryButton: {
    border: 0,
    color: '#4a271b',
    backgroundColor: colors.coralSoft,
    ':hover': { backgroundColor: '#f7ae9d' },
  },
  secondaryButton: {
    border: 0,
    color: '#fff',
    backgroundColor: colors.green,
    ':hover': { backgroundColor: '#3b5048' },
  },
  emptyCopy: { maxWidth: 440, marginTop: 16, color: colors.muted, fontSize: 13, lineHeight: 1.55 },
  dishesSection: { marginTop: 48, scrollMarginTop: 20, [tablet]: { marginTop: 72 } },
  dishCards: {
    display: 'grid',
    gridAutoColumns: 'minmax(210px, 75%)',
    gridAutoFlow: 'column',
    gap: 12,
    overflowX: 'auto',
    padding: '2px 2px 12px',
    scrollSnapType: 'x mandatory',
    [tablet]: {
      gridAutoColumns: 'auto',
      gridAutoFlow: 'row',
      gridTemplateColumns: 'repeat(3, minmax(0, 1fr))',
      overflowX: 'visible',
    },
  },
  dishCard: {
    position: 'relative',
    minHeight: 190,
    padding: 18,
    overflow: 'hidden',
    borderRadius: 23,
    backgroundColor: '#f5d8a8',
    scrollSnapAlign: 'start',
  },
  dishCardAlt: { backgroundColor: '#cfe5d6' },
  miniPlate: {
    position: 'absolute',
    top: 15,
    right: 15,
    display: 'inline-flex',
    width: 42,
    height: 42,
    color: 'rgb(38 53 47 / 24%)',
  },
  dishTitle: {
    maxWidth: '75%',
    fontFamily: display,
    fontSize: 18,
    lineHeight: 1.1,
    letterSpacing: '-0.035em',
  },
  dishNotes: { maxWidth: '82%', marginTop: 8, color: '#657068', fontSize: 11, lineHeight: 1.45 },
  dishStat: {
    position: 'absolute',
    bottom: 17,
    left: 18,
    color: '#657068',
    fontSize: 10,
    fontWeight: 700,
  },
  addDishDisclosure: {
    marginTop: 15,
    border: `1px solid ${colors.line}`,
    borderRadius: 20,
    backgroundColor: 'rgb(255 255 255 / 60%)',
  },
  addDishSummary: {
    display: 'flex',
    minHeight: 54,
    alignItems: 'center',
    gap: 8,
    padding: '0 17px',
    color: colors.green,
    fontSize: 12,
    fontWeight: 800,
    listStyle: 'none',
    cursor: 'pointer',
  },
  addDishForm: {
    display: 'grid',
    gap: 13,
    padding: '4px 17px 18px',
    [tablet]: { gridTemplateColumns: '1fr 1fr auto', alignItems: 'end' },
  },
  optional: { color: colors.muted, fontWeight: 400 },
  historySection: { marginTop: 48, [tablet]: { marginTop: 72 } },
  historyList: {
    display: 'grid',
    overflow: 'hidden',
    border: `1px solid ${colors.line}`,
    borderRadius: 22,
    backgroundColor: 'rgb(255 255 255 / 58%)',
  },
  historyRow: {
    display: 'grid',
    minHeight: 64,
    gridTemplateColumns: '30px minmax(0, 1fr) auto',
    gap: 11,
    alignItems: 'center',
    padding: '0 15px',
    borderBottom: `1px solid ${colors.line}`,
    ':last-child': { borderBottom: 0 },
  },
  historyMark: {
    display: 'grid',
    width: 27,
    height: 27,
    placeItems: 'center',
    borderRadius: '50%',
    color: colors.green,
    backgroundColor: colors.mint,
  },
  historyName: { fontSize: 12, fontWeight: 700 },
  historyDate: { color: colors.muted, fontSize: 10 },
  historyEmpty: { margin: 0, padding: '20px 16px' },
  bottomNav: {
    position: 'fixed',
    zIndex: 10,
    right: 0,
    bottom: 0,
    left: 0,
    display: 'grid',
    height: 78,
    gridTemplateColumns: 'repeat(3, 1fr)',
    padding: '10px 28px max(12px, env(safe-area-inset-bottom))',
    borderTop: `1px solid ${colors.line}`,
    backgroundColor: 'rgb(255 254 249 / 94%)',
    backdropFilter: 'blur(12px)',
    [tablet]: { display: 'none' },
  },
  navItem: {
    display: 'grid',
    gap: 3,
    justifyItems: 'center',
    color: colors.muted,
    fontSize: 9,
    fontWeight: 800,
    textDecoration: 'none',
  },
  setupShell: { display: 'grid', minHeight: '100vh', padding: 18, placeItems: 'center' },
  setupCard: {
    position: 'relative',
    width: 'min(520px, 100%)',
    padding: '30px 24px',
    overflow: 'hidden',
    border: `1px solid ${colors.line}`,
    borderRadius: 28,
    backgroundColor: colors.white,
    boxShadow: '0 18px 50px rgb(73 58 39 / 10%)',
    [tablet]: { padding: 44 },
  },
  setupEyebrow: { marginTop: 42 },
  setupTitle: {
    fontFamily: display,
    fontSize: 'clamp(32px, 8vw, 50px)',
    lineHeight: 1,
    letterSpacing: '-0.06em',
  },
  setupCopy: { marginTop: 18, color: colors.muted, fontSize: 14, lineHeight: 1.65 },
  signInButton: {
    display: 'inline-flex',
    minHeight: 48,
    alignItems: 'center',
    justifyContent: 'center',
    marginTop: 26,
    padding: '0 19px',
    borderRadius: 999,
    color: '#fff',
    backgroundColor: colors.green,
    fontSize: 13,
    fontWeight: 800,
    textDecoration: 'none',
    ':hover': { backgroundColor: '#3b5048' },
  },
})
